name: Pipeline Samuel Kraut

on:
  push:
    branches:
      - main
      - edit

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_TAG: ghcr.io/ci-cd-2024-dhbw-hdh/samuel.kraut
  #K8_NAMESPACE: butter-chicken
  #K8_SECRET_NAME: regcred



jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm i

      - name: Svelte check
        run: npm run check

      - name: format check
        run: npm run format:check

      - name: eslint check
        run: npm run lint

      - name: Run Tests
        run: npm run test
        
      - name: Build
        run: npm run build

  build-and-push-image:
    # needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # automatisch
          password: ${{ secrets.GITHUB_TOKEN }} # automatisch

      - name: build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/ci-cd-2024-dhbw-hdh/samuel.kraut:latest"
            ghcr.io/ci-cd-2024-dhbw-hdh/samuel.kraut:${{ github.sha }}" # sha ist git commit hash
  
  
  # deploy-k8:
  #   needs: build-and-push-image
  #   runs-on: ubuntu-latest
  #   permissions: # Info Github Token Premissions: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  #     id-token: write
  #     contents: read
  #     actions: read
  #     packages: read
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
      
  #     - uses: azure/setup-kubectl@v2.0

  #     - uses: Azure/k8s-set-context@v2
  #       with:
  #         kubeconfig: ${{ secrets.KUBE_CONFIG }} # anlegen https://github.com/CI-CD-2024-DHBW-HDH/butter-chicken/settings/secrets/actions/new
  #         # Kubeconfig einfach ins Value einfügen

  #     - name: create image registry secret for kubernetes
  #       uses: Azure/k8s-create-secret@v1.1
  #       with:
  #         namespace: $K8_NAMESPACE
  #         container-registry-url: $CONTAINER_REGISTRY
  #         container-registry-username: ${{ github.actor }}
  #         container-registry-password: ${{ secrets.GITHUB_TOKEN }} #automatisch (durch Premission im job möglich) # Mit ${{ secrets.PULL_TOKEN }} muss selbst angelet werden https://github.com/settings/tokens/new (read:packages = true)
  #         secret-name: $K8_SECRET_NAME

  #     - name: deploy deployment and service
  #       uses: Azure/k8s-deploy@v4
  #       with:
  #         namespace: $K8_NAMESPACE
  #         manifests: |
  #           deployment/deployment1.yaml
  #           deployment/service1.yaml
  #         images: |
  #           $IMAGE_TAG:${{ github.sha }} # sha ist git commit hash. Das Tag von Image wird hiermit im deployment überschrieben. Sichert das gerade gepushte Image aus der Pipeline verwendet wird
  #         imagepullsecrets: |
  #           $K8_SECRET_NAME